name: Discord Notify Commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Discord Commits
      uses: Sniddl/discord-commits@1.3
      with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "\n<@&876841382579404801>\nRepositorio Atualizado: **{{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}**.**\nAlterações desse commit:**\n{{ github.context.payload.compare }}"
          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'
          last-commit-only: false
